mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('relatorioapp.urls')),
    path('',RedirectView.as_view(url='home/')),
    path('accounts/',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/relatorioapp/urls.py
from django.urls import path
from . import views


app_name = "relatorio"

urlpatterns = [

    # URLs associadas ao modelo Relatorio

    path('relatorio/add/', views.RelatorioCreateView.as_view(), name='create_relatorio'),
    path('relatorio/list/', views.RelatorioListView.as_view(), name='list_relatorio'),
    path('relatorio/detail/<int:pk>', views.RelatorioDetailView.as_view(), name='detail_relatorio'),
    #path('relatorio/update/<int:pk>', views.RelatorioUpdateView.as_view(), name='update_relatorio'),
    path('relatorio/delete/<int:pk>', views.RelatorioDeleteView.as_view(), name='delete_relatorio'),
    path('home/', views.home, name='home'),
    path('conceitos-audiencia/', views.conceitospage, name='conceitos_audiencia'),

    # URLs associadas ao modelo Programacao

    path('programacao/add/', views.ProgramacaoCreateView.as_view(), name='create_programacao'),
    path('programacao/list/', views.ProgramacaoListView.as_view(), name='list_programacao'),
    path('programacao/detail/<int:pk>', views.ProgramacaoDetailView.as_view(), name='detail_programacao'),
    #path('programacao/update/<int:pk>', views.ProgramacaoUpdateView.as_view(), name='update_programacao'),
    path('programacao/delete/<int:pk>', views.ProgramacaoDeleteView.as_view(), name='delete_programacao'),

    # URL do login

    path('signup/', views.SignUpView.as_view(), name='signup'),

    # URL da tela de contato
    path('contato/', views.contato, name='contato'),
    path('sucesso/', views.sucesso, name='sucesso'),

    # URL do Carrossel
    path('carrossel/add/', views.CarrosselCreateView.as_view(), name='create_carrossel'),
    path('outraview/', views.outraview, name='outra_view'),
    path('carrossel/list/', views.CarrosselListView.as_view(), name='list_carrossel'),
    path('carrossel/delete/<int:pk>', views.CarrosselDeleteView.as_view(), name='delete_carrossel'),
    path('carrossel/update/<int:pk>', views.CarrosselUpdateView.as_view(), name='update_carrossel'),
]

mysite/relatorioapp/forms.py
from django import forms 
from relatorioapp.models import Relatorio, Programacao, Carrossel
#from crispy_forms.helper import FormHelper


class RelatorioForm(forms.ModelForm):
    class Meta:
        model = Relatorio
        fields = '__all__'
        widgets = {
            "data": forms.DateInput(attrs={'type': 'date', 'class':'form-control'} ),
            "titulo":forms.TextInput(attrs={'class':'form-control'}),
            "descricao":forms.Textarea(attrs={'class':'form-control', 'rows':5}),
            "tipo":forms.Select(attrs={'class':'form-select'}),
            "autor":forms.TextInput(attrs={'class':'form-control'}),
            "paragrafo1":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo2":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo3":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo4":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo5":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "arquivo":forms.FileInput(attrs={'class':'form-control'}),
            "imagem_thumb":forms.FileInput(attrs={'class':'form-control'}),
            "imagem_post":forms.FileInput(attrs={'class':'form-control'}),
            "legenda_imagem":forms.Textarea(attrs={'class':'form-control', 'rows':2}),
            "url":forms.TextInput(attrs={'class':'form-control'}),
        }



class ProgramacaoForm(forms.ModelForm):
    class Meta:
        model = Programacao
        fields = '__all__'
        titulo= forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
        widgets = {
            "data": forms.DateInput(attrs={'type': 'date', 'class':'form-control'} ),
            "titulo":forms.TextInput(attrs={'class':'form-control'}),
            "descricao":forms.Textarea(attrs={'class':'form-control', 'rows':5}),
            "tipo":forms.Select(attrs={'class':'form-select'}),
            "autor":forms.TextInput(attrs={'class':'form-control'}),
            "paragrafo1":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo2":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo3":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo4":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "paragrafo5":forms.Textarea(attrs={'class':'form-control', 'rows':8}),
            "arquivo":forms.FileInput(attrs={'class':'form-control'}),
            "imagem_thumb":forms.FileInput(attrs={'class':'form-control'}),
            "imagem_post":forms.FileInput(attrs={'class':'form-control'}),
            "legenda_imagem":forms.Textarea(attrs={'class':'form-control', 'rows':2}),
        }
        # helper = FormHelper()
        def __init__(self, *args, **kwargs):
            super(ProgramacaoForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'


class CarrosselForm(forms.ModelForm):
    class Meta:
        model = Carrossel
        fields = '__all__'
        widgets = {
            "imagem":forms.FileInput(attrs={'class':'form-control'}),
            "legenda1":forms.Textarea(attrs={'class':'form-control', 'rows':1}),
            "legenda2":forms.Textarea(attrs={'class':'form-control', 'rows':2}),
        }




#===============================================================
class ContactForm(forms.Form):
	first_name = forms.CharField(max_length = 50)
	last_name = forms.CharField(max_length = 50)
	email_address = forms.EmailField(max_length = 150)
	message = forms.CharField(widget = forms.Textarea, max_length = 2000)

mysite/relatorioapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.urls import reverse, reverse_lazy
from relatorioapp.models import Relatorio, Programacao, Carrossel
from relatorioapp.forms import RelatorioForm, ProgramacaoForm, ContactForm, CarrosselForm
from django.views.generic import CreateView,DetailView,ListView 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ContactForm




########################################################################################################################
#
#                                           Views e Funções associados ao modelo relatorio
#
########################################################################################################################


# Definição da função que fará o upload das imagens
def image_upload_view_relatorio(request):
    """Process images uploaded by users"""
    if request.method == 'POST':
        form_rel = RelatorioForm(request.POST, request.FILES)
        if form_rel.is_valid():
            form_rel.save()
            # Get the current instance object to display in the template
            img_obj = form_rel.instance
            return render(request, 'relatorioapp/relatorio_list.html', {'form1': form_rel, 'img_obj': img_obj})
    else:
        form_rel = RelatorioForm()
    return render(request, 'relatorioapp/relatorio_list.html', {'form1': form_rel})



# Definindo a função que fará o upload do PDF
def pdf_upload_view_relatorio(request):
    """Process pdfd uploaded by users"""
    if request.method == 'POST':
        form_rel1 = RelatorioForm(request.POST, request.FILES)
        if form_rel1.is_valid():
            form_rel1.save()
            # Get the current instance object to display in the template
            pdf_obj = form_rel1.instance
            return render(request, 'relatorioapp/relatorio_list.html', {'form': form_rel1, 'pdf_obj': pdf_obj})
    else:
        form_rel1 = RelatorioForm()
    return render(request, 'relatorioapp/relatorio_list.html', {'form': form_rel1})


#-------------------    Criando as views usando o CBV    -------------------

class RelatorioCreateView(LoginRequiredMixin, CreateView):
    model = Relatorio
    form_class = RelatorioForm
    template_name = 'relatorioapp/relatorio_form.html'
    success_url = reverse_lazy('relatorio:home')


class RelatorioListView(ListView):
    model = Relatorio
    #permission_required = "app.view_relatorio_list"
    queryset = Relatorio.objects.order_by('data')
    #queryset = Relatorio.objects.all()
    context_object_name = "lista_de_relatorios"

    def get_queryset(self):
        tipo = self.request.GET.get('tipo')
        if tipo:
            return Relatorio.objects.filter(tipo=tipo)
        else:
            return Relatorio.objects.filter(tipo=tipo)
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tipo = self.request.GET.get('tipo')
                
        if tipo == 'Noticia':
            context['tipo_nome']='noticias'         
            
        elif tipo == 'Pesquisa':
            context['tipo_nome']='pesquisa'

        elif tipo == 'Pipacast':
            context['tipo_nome']='pipacast'

        elif tipo == 'Relatorio_de_audiencia':
            context['tipo_nome']='relatorio_de_audiencia'
            #context['preposicao'] =  'dos'
        return context


class RelatorioDetailView(DetailView):
    model = Relatorio


class RelatorioUpdateView(LoginRequiredMixin, UpdateView):
    model = Relatorio
    fields = '__all__'
    success_url = reverse_lazy('relatorio:list_relatorio')


class RelatorioDeleteView(LoginRequiredMixin, DeleteView):
    model = Relatorio
    success_url = reverse_lazy('relatorio:list_relatorio')


class SignUpView(CreateView):
    form_class = UserCreationForm 
    success_url = reverse_lazy('login')
    template_name = 'relatorioapp/signup.html'



#--------------------------    Criando a view usando Função    ------------------
#@login_required 
def home(request):
    relatorios = [
        {'nome_modelo': Relatorio._meta.verbose_name_plural, 'registros': Relatorio.objects.all()},
        {'nome_modelo': Programacao._meta.verbose_name_plural, 'registros': Programacao.objects.all()},
        {'nome_modelo': Carrossel._meta.verbose_name_plural, 'carrosseis':Carrossel.objects.all()},
    ]
    
    return render(request, 'relatorioapp/home.html', {'relatorios':relatorios})


def conceitospage(request):
    return render(request, 'relatorioapp/conceitos-audiencia.html')


def outraview(request):
    relatorios = Carrossel.objects.all()
    return render(request, 'relatorioapp/outraview.html', {'relatorios':relatorios})
########################################################################################################################
#
#                                           Views e Funções associados ao modelo programação
#
########################################################################################################################


# Definição da função que fará o upload das imagens
def image_upload_view_programacao(request):
    """Process images uploaded by users"""
    if request.method == 'POST':
        form_prg = ProgramacaoForm(request.POST, request.FILES)
        if form_prg.is_valid():
            form_prg.save()
            # Get the current instance object to display in the template
            img_obj = form_prg.instance
            return render(request, 'relatorioapp/programacao_list.html', {'form1': form_prg, 'img_obj': img_obj})
    else:
        form_prg = ProgramacaoForm()
    return render(request, 'relatorioapp/programacao_list.html', {'form1': form_prg})



# Definindo a função que fará o upload do PDF
def pdf_upload_view_programacao(request):
    """Process pdfd uploaded by users"""
    if request.method == 'POST':
        form_prg1 = ProgramacaoForm(request.POST, request.FILES)
        if form_prg1.is_valid():
            form_prg1.save()
            # Get the current instance object to display in the template
            pdf_obj = form_prg1.instance
            return render(request, 'relatorioapp/programacao_list.html', {'form': form_prg1, 'pdf_obj': pdf_obj})
    else:
        form_prg1 = ProgramacaoForm()
    return render(request, 'relatorioapp/programacao_list.html', {'form': form_prg1})


# --------------------    Criando as views usando o CBV   --------------------------------------------------


class ProgramacaoCreateView(LoginRequiredMixin, CreateView):
    model = Programacao
    form_class = ProgramacaoForm
    template_name = 'relatorioapp/programacao_form.html'
    success_url = reverse_lazy('relatorio:home')


class ProgramacaoListView(ListView):
    model = Programacao
    queryset = Programacao.objects.order_by('data')
    #queryset = Relatorio.objects.all()
    context_object_name = "lista_da_programacao"

    def get_queryset(self):
        tipo = self.request.GET.get('tipo')
        if tipo:
            return Programacao.objects.filter(tipo=tipo)
        else:
            #return Programacao.objects.filter(tipo=tipo)
            return Programacao.objects.all()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tipo = self.request.GET.get('tipo')
        subtipo = self.request.GET.get('subtipo')
                    
        if tipo == 'Programacao':
            context['tipo_nome']='programacao'

        elif tipo == 'Pipacast':
            context['tipo_nome']='pipacast'

        if subtipo == 'pdf':
            context['subtipo_nome']='pdf'

        elif subtipo =='blog':
            context['subtipo_nome']='blog'

        return context


class ProgramacaoDetailView(DetailView):
    model = Programacao


class ProgramacaoUpdateView(LoginRequiredMixin, UpdateView):
    model = Programacao
    fields = '__all__'
    success_url = reverse_lazy('relatorio:list_programacao')


class ProgramacaoDeleteView(LoginRequiredMixin, DeleteView):
    model = Programacao
    success_url = reverse_lazy('relatorio:list_programacao')


########################################################################################################################
#
#                                           View do Forms para contato e receber e-mail
#
##################################################################################################


def contato(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = "Website Inquiry" 
			body = {
			'first_name': form.cleaned_data['first_name'], 
			'last_name': form.cleaned_data['last_name'], 
			'email': form.cleaned_data['email_address'], 
			'message':form.cleaned_data['message'], 
			}
			message = "\n".join(body.values())

			try:
				send_mail(subject, message, 'pipapesquisas@rebahia.com.r', ['pipapesquisas@gmail.com']) 
			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			return redirect ("relatorio:home")
      
	form = ContactForm()
	return render(request, "relatorioapp/contato.html", {'form':form})

def sucesso(request):
    return render(request, 'relatorioapp/sucesso.html')





########################################################################################################################
#
#                                           Views e Funções associados ao modelo Carrossel
#
########################################################################################################################

# Definição da função que fará o upload das imagens

mysite/relatorioapp/templates/relatorioapp/carrossel_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'relatorioapp\style.css'%}">
    {% block titulo_page %}
    <title>PIPA</title>
    {%  endblock %}
</head>
<body>

{% comment %} 
  Modificando a barra de navegação a depender do estado do usário:
  Logado ou não-logado.
{% endcomment %}
{% if user.is_authenticated%}
{% block header_logout %}
    <header class="header-1">
    <a href="#" class="logo">PIPA PESQUISA</a>
     <i class='bx bx-menu' id="menu-icon"></i>
      <nav class="navbar">
          <a href="" class="active">Olá, {{user.get_full_name}}!</a>
          <a href="{% url 'relatorio:home'%}">HOME</a>
          <a href="{% url 'relatorio:contato'%}">CONTATO</a>
          <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">LOGOUT</button></a>
      </nav>
      </header>
  {% endblock %}
{% else %}
{% block header_login %}
    <header class="header-1">
        <a href="#" class="logo">PIPA PESQUISA</a>

        <i class='bx bx-menu' id="menu-icon"></i>

        <nav class="navbar">
            <a href="{% url 'relatorio:home'%}" class="active">HOME</a>
            <a href="{% url 'relatorio:list_relatorio'%}?tipo=Noticia">NOTICIAS</a>
            <a href="#">CONTATO</a>
            <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-light">LOGIN</button></a>
        </nav>
    </header>
{% endblock %}
{% endif %}

{% block submenu %}
<div class="submenu">
  <a href="{% url 'relatorio:list_relatorio'%}?tipo=Pesquisa" class="botao-submenu">PESQUISAS</a>
  <a href="{% url 'relatorio:conceitos_audiencia'%}" class="botao-submenu">CONCEITOS</a>
  <a href="{% url 'relatorio:list_programacao'%}?tipo=Programacao" class="botao-submenu">PROGRAMAÇÃO</a>
  <a href="{% url 'relatorio:list_programacao'%}?tipo=Pipacast" class="botao-submenu">PIPACAST</a>
  <a href="{% url 'relatorio:list_relatorio'%}?tipo=Noticia" class="botao-submenu">NOTÍCIA</a>
  {% if user.is_authenticated%}
    {% if user.groups.all %} 
      {% for group in user.groups.all %}
        {% if group.name == 'leitor' %}
            <a href="{% url 'relatorio:list_relatorio'%}?tipo=Relatorio_de_audiencia" class="botao-submenu">RELATÓRIOS</a>
        {% endif %}
        {% if group.name == 'editor' or group.name == 'root' %}
          <a href="{% url 'relatorio:list_relatorio'%}?tipo=Relatorio_de_audiencia" class="botao-submenu">RELATÓRIOS</a>
          <a href="{% url 'relatorio:create_relatorio'%}" class="botao-submenu">ADD RELATÓRIO</a>
          <a href="{% url 'relatorio:create_programacao'%}" class="botao-submenu">ADD PROGRAMAÇÂO</a>
          <a href="{% url 'relatorio:create_carrossel'%}" class="botao-submenu">CARROSSEL</a>
        {% endif %}
      {% endfor %}
    {% endif %}
  {% endif %}
</div>
{% endblock %}
    
<br>    <br>    <br>    <br>    <br>    <br>    <br> <br> 


    <div class='container'>
      {% if user.is_authenticated %}
        {% if user.groups.all %}
          {% for group in user.groups.all %}
            {% if group.name != 'leitor' %}
              <h1 class="t-pg-conceitos"><b>Página de Exclusão de conteúdo</b></h1>
              <br>              
              <h3>Uma vez excluído não pode ser recuperado!</h3>
              <br>
              <form action="" method="post">
                  {% csrf_token %}
                  <button class="btn btn-danger" type="submit"> Confirme a Exclusão</button>
              </form>
            {% else %}
              <h1>Acesso restrito!</h1>
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endif %}
    </div>


    




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    <script src="{% static 'relatorioapp\script.js'%}"></script>
</body>
</html>

mysite/relatorioapp/templates/relatorioapp/carrossel_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'relatorioapp/style.css'%}">
    {% block titulo_page %}
    <title>Adicione imagem ao carrossel</title>
    {%  endblock %}
</head>
<body>


{% comment %} 
  Modificando a barra de navegação a depender do estado do usário:
  Logado ou não-logado.
{% endcomment %}
{% if user.is_authenticated%}
{% block header_logout %}
    <header class="header-1">
    <a href="#" class="logo">PIPA PESQUISA</a>
     <i class='bx bx-menu' id="menu-icon"></i>
      <nav class="navbar">
          <a href="" class="active">Olá, {{user.get_full_name}}!</a>
          <a href="{% url 'relatorio:home'%}">HOME</a>
          <a href="{% url 'relatorio:contato'%}">CONTATO</a>
          <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">LOGOUT</button></a>
      </nav>
      </header>
  {% endblock %}
{% else %}
{% block header_login %}
    <header class="header-1">
        <a href="#" class="logo">PIPA PESQUISA</a>

        <i class='bx bx-menu' id="menu-icon"></i>

        <nav class="navbar">
            <a href="{% url 'relatorio:home'%}" class="active">HOME</a>
            <a href="{% url 'relatorio:contato'%}">CONTATO</a>
            <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-light">LOGIN</button></a>
        </nav>
    </header>
{% endblock %}
{% endif %}

{% block submenu %}
<div class="submenu">
  <a href="{% url 'relatorio:list_relatorio'%}?tipo=Pesquisa" class="botao-submenu">PESQUISAS</a>
  <a href="{% url 'relatorio:conceitos_audiencia'%}" class="botao-submenu">CONCEITOS</a>
  <a href="{% url 'relatorio:list_programacao'%}?tipo=Programacao" class="botao-submenu">PROGRAMAÇÃO</a>
  <a href="{% url 'relatorio:list_programacao'%}?tipo=Pipacast" class="botao-submenu">PIPACAST</a>
  <a href="{% url 'relatorio:list_relatorio'%}?tipo=Noticia" class="botao-submenu">NOTÍCIA</a>
  {% if user.is_authenticated%}
    {% if user.groups.all %} 
      {% for group in user.groups.all %}
        {% if group.name == 'leitor' %}
            <a href="{% url 'relatorio:list_relatorio'%}?tipo=Relatorio_de_audiencia" class="botao-submenu">RELATÓRIOS</a>
        {% endif %}
        {% if group.name == 'editor' or group.name == 'root' %}
          <a href="{% url 'relatorio:list_relatorio'%}?tipo=Relatorio_de_audiencia" class="botao-submenu">RELATÓRIOS</a>
          <a href="{% url 'relatorio:create_relatorio'%}" class="botao-submenu">ADD RELATÓRIO</a>
          <a href="{% url 'relatorio:create_programacao'%}" class="botao-submenu">ADD PROGRAMAÇÂO</a>
          <a href="{% url 'relatorio:create_carrossel'%}" class="botao-submenu">CARROSSEL</a>
        {% endif %}
      {% endfor %}
    {% endif %}
  {% endif %}
</div>
{% endblock %}


<br><br><br><br><br><br><br><br>

{% if user.is_authenticated %}
  {% if user.groups.all %}
    {% for group in user.groups.all %}
      {% if group.name != 'leitor' %}
        {% block formulario_Criar_Relatorio %}
          <div class="container">
            <h1 classe="title">Use esta página para adicionar o conteúdo do carrossel:</h1>
            <br>
            <p>Clique no botão para atualizar conteúdo já adicionado.  <a href={% url 'relatorio:list_carrossel' %}><button type="button" class="btn btn-outline-primary btn-sm"> Ajuste</button></a></p>
            
            {% comment %} <li class="texto"><strong>Relatório de audiência - Arquivo PDF</strong></li>
            <li class="texto"><strong>Notícia - Matéria no formato de Blog</strong></li>
            <li class="texto"><strong>Pesquisa - Matéria no formato de Blog</strong></li>
            <li class="texto"><strong>Outro - Hospedar conteúdo externo</strong></li> {% endcomment %}
          </div>
          <br>
          <div class="container">
            <div class="form-group">
                <form method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class='mb-3'>
                      <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label><br>
                      {{ field }}
                      {{ field.errors }}
                    </div>
                    {% endfor %}       
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
            </div>
          </div>
        {% endblock%}
      {% else %}
        <div class='container'>
          <h1>Você não tem permissão para ver este conteúdo.<h1>
        <div>
      {% endif %}
    {% endfor %}
  {% endif %}
{% endif %}

mysite/relatorioapp/templates/relatorioapp/signup.html
<h1>Esta é a tela do login</h1>

mysite/relatorioapp/templates/relatorioapp/sucesso.html
<h1>O contato foi estabelecido com sucesso!</h1>